package com.example.demo.process

//list any import classes here.

import com.example.demo.Test

//declare any global variables here


rule "value for a"

	//for bpmn to link ruleflow-group
	ruleflow-group "helloworldgroup"
    when
        //conditions
        testObject: Test(type=="a")
    then
        //actions
        testObject.setValue("HelloWorldB: testTypeA");

end

rule "value for b"
    //include attributes such as "salience" here...
    //no-loop true
	ruleflow-group "helloworldgroup"
    when
        //conditions
        testObject: Test(type=="b")
    then
        //actions
		testObject.setValue("HelloWorldB: testTypeB");
end

rule "value for type others"
    //include attributes such as "salience" here...
    //no-loop true
	ruleflow-group "helloworldgroup"
    when
        //conditions
        testObject: Test(type!="a" && type!="b")
    then
        //actions
		testObject.setValue("HelloWorldB: testTypeOthers");
end
