package com.myspace.helloworld;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("data object one")
public class Data_obj_one implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("type")
    private java.lang.String type;
    @org.kie.api.definition.type.Label("value")
    private java.lang.String value;

    public Data_obj_one() {
    }

    public java.lang.String getType() {
        return this.type;
    }

    public void setType(java.lang.String type) {
        this.type = type;
    }

    public java.lang.String getValue() {
        return this.value;
    }

    public void setValue(java.lang.String value) {
        this.value = value;
    }

    public String toString() {
        return "Data_obj_one [type=" + type + ", value=" + value + "]";
    }

    public Data_obj_one(java.lang.String type, java.lang.String value) {
        this.type = type;
        this.value = value;
    }

}